### ISSUE TITLE
Description of code and classification

### ISSUE THREAD

**Issue by Beliavsky** [endeve/thornado#23]
I am listing Fortran codes by category at https://github.com/Beliavsky/Fortran-code-on-GitHub and would like to add thornado. Could you provide a short description and suggest a category for the code? Thanks.

**Comment by dunhamsj** [comment]
Hi! Sorry for the delay in addressing this issue. Based on the categories listed on the repo you linked, I would classify thornado under "Astronomy & Astrophysics".

As for a description, it is a neutrino radiation-hydrodynamics code aiming to simulate core-collapse supernovae using discontinuous Galerkin methods

**Comment by Beliavsky** [comment]
added, thanks
